### ISSUE TITLE
Name of project template?

### ISSUE THREAD

**Issue by vLGrok** [emerbrito/Windows-Service-Plus#2]
When creating a new project from VS 2015, under what name should we find this new template?  I've installed "Windows Service Plus" in extensions and updates, yet after that, I'm still only finding the intrinsic windows service project.

**Comment by emerbrito** [comment]
Thank you for your feedback. You should be able to find it in the New Project dialog under "Templates/C#". Make sure you select at least .NET 4.6 as the target framework.

Another easy way is to open the New Project dialog (VS 2015) and on the right top corner enter "Service Plus" in the "Search Installed Templates" field. This will filter the output and you will be able to spot it (the project template).  Again, make sure target framework is at least .NET 4.6.

**Comment by vLGrok** [comment]
Targeting .NET 4.6+ solved the problem. Template indeed shows up as "Windows Service Plus".
