### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by vLGrok** [emerbrito/Windows-Service-Plus#3]
Running (F5) from IDE works great.  Any tips on installation?
Tried:
installutil FileService\bin\Debug\DocumentExport.FileService.exe
Got:
No public installers with the RunInstallerAttribute.Yes attribute could be found.
Remove InstallState file because there are no installers.
The Commit phase completed successfully.
The transacted install has completed.

How to add the service process installer and service installer? From the looks of Program.cs, I was expecting service installation when I ran the project. But I'd also want to be able to script the install from command line, as it's going on remote machine.

**Comment by emerbrito** [comment]
Please look at the TopShelf documentation for additional information:
[http://docs.topshelf-project.com/en/latest/overview/commandline.html#examples](url)

Basically you can use the command line to install, uninstall and configure the service.
