### ISSUE TITLE
Install fails in VS2019

### ISSUE THREAD

**Issue by chasingcode** [emerbrito/Windows-Service-Plus#7]
The Microsoft.VisualStudio.Component.CoreEditor prerequisite in the vsixmanifest should have an open-ended upper bound according to Mads Kristensen:
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/
After I edited that file locally, I was able to successfully install the extension in VS2019 Community.
I submitted a PR with that change. #6

**Comment by emerbrito** [comment]
Fixed on #6

**Comment by emerbrito** [comment]
I merged your pull request and update the extension in the marketplace.
Thanks.
